car_1/urls.py
from unicodedata import name
from django.urls import path

from car_1.models import car_company, car_info, model_info
from . import views
from django.http import JsonResponse

def get_cars_ajax(request):
    data = []
    if request.method == "POST":
        company_id = request.POST['company_id']
        try:
            company1 = car_company.objects.filter(name = company_id).first()
            car = car_info.objects.filter(company = company1)
        except Exception:
            return JsonResponse(data,safe=False)
        return JsonResponse(list(car.values('name')), safe = False)
def get_models_ajax(request):
    data = []
    if request.method == "POST":
        car_id = request.POST['car_id']
        try:
            car1 = car_info.objects.filter(name = car_id).first()
            model = model_info.objects.filter(car = car1)
        except Exception:
            return JsonResponse(data,safe=False)
        return JsonResponse(list(model.values('name')), safe = False)
urlpatterns = [
    path('home/',views.home_page,name = 'home_page'),
    path('login/',views.loginuser,name = 'login'),
    path('logout/',views.logoutuser,name = 'logout'),
    path('signup/',views.signup,name = 'signup'),
    path('sell/',views.sell,name = 'sell'),
    path('buy/',views.buy,name = 'buy'),
    path('profile/',views.profile,name = 'profile'),
    path(r'^process_request/(?P<id>\d+)$',views.process,name = 'process_request'),
    path('comparo/',views.comparo,name = 'comparo'),
    path('suggest/',views.suggest,name = 'suggest'),
    path('get-cars-ajax/',get_cars_ajax, name="get_cars_ajax"),
    path('buy/sort_by_popularity/',views.sort_by_popularity,name = 'sort_by_popularity'),
    path('buy/sort_by_lowest/',views.sort_by_lowest,name = 'sort_by_lowest'),
    path('buy/sort_by_highest/',views.sort_by_highest,name = 'sort_by_highest'),
    path('get-models-ajax/',get_models_ajax, name="get_models_ajax")
]

car_app/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('car_1.urls'))
]

car_1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class car_company(models.Model):
    name = models.CharField(max_length= 50,null=True)
    def __str__(self):
        return self.name
class car_info(models.Model):
    name = models.CharField(max_length= 50,null=True)
    company = models.ForeignKey(car_company,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name
class user_info(models.Model):
    username = models.CharField(max_length= 50,null=True)
    mail = models.EmailField(null=True)
    first_name = models.CharField(max_length= 50,null=True)
    last_name = models.CharField(max_length= 50,null=True)
    pwd = models.CharField(max_length= 50,null=True)
    def __str__(self):
        return self.username
class Used_Car_Details(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    status = models.IntegerField(null = True)
    Price = models.CharField(max_length = 30,null=True)
    Mobile_No = models.PositiveBigIntegerField(null=True)
    Company = models.CharField(max_length = 30,null=True)
    Car_name = models.CharField(max_length= 30,null=True)
    Car_Model = models.CharField(max_length= 20,null=True)
    Car_Year = models.IntegerField(null=True)
    reg_no = models.IntegerField(null = True)
    Car_KM = models.IntegerField(null=True)
    photo1 = models.ImageField(upload_to = '',null = True,blank = True)
    photo2 = models.ImageField(upload_to = '',null = True,blank = True)
    photo3 = models.ImageField(upload_to = '',null = True,blank = True)
    photo4 = models.ImageField(upload_to = '',null = True,blank = True)
    photo5 = models.ImageField(upload_to = '',null = True,blank = True)
    photo6 = models.ImageField(upload_to = '',null = True,blank = True)
    photo7 = models.ImageField(upload_to = '',null = True,blank = True)
    photo8 = models.ImageField(upload_to = '',null = True,blank = True)
    photo9 = models.ImageField(upload_to = '',null = True,blank = True)
    photo10 = models.ImageField(upload_to = '',null = True,blank = True)
    def __str__(self) -> str:
        return str(self.id)
class model_info(models.Model):
    name = models.CharField(max_length= 50,null=True)
    car = models.ForeignKey(car_info,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name
class car_details(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 50,null=True)
    Price = models.CharField(max_length = 50,null=True)
    engine =  models.CharField(max_length = 50,null=True)
    powertorque = models.CharField(max_length = 50,null=True)
    gearbox = models.CharField(max_length = 50,null=True)
    fueleconomy = models.CharField(max_length = 50,null=True)
    wheelbase = models.CharField(max_length = 50,null=True)
    infoitainment = models.CharField(max_length = 50,null=True)
    def __str__(self):
        return str(self.id)
class suggest_details(models.Model):
    name = models.CharField(max_length = 50,null=True)
    Price_Range = models.CharField(max_length = 50,null=True)
    car_type = models.CharField(max_length = 50,null=True)
    Price = models.CharField(max_length = 50,null=True)
    Rating = models.CharField(max_length = 50,null=True)
    car_image = models.ImageField(upload_to = '',null = True,blank = True)
    pro1 = models.CharField(max_length = 50,null=True)
    pro2 = models.CharField(max_length = 50,null=True)
    pro3 = models.CharField(max_length = 50,null=True)
    con1 = models.CharField(max_length = 50,null=True)
    con2 = models.CharField(max_length = 50,null=True)
    def __str__(self):
        return str(self.name)
class buy_details(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    car = models.ForeignKey(Used_Car_Details,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return str(self.id)

templates/buy.html
{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .flexx_2{
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            padding : 2% 2% 2% 2%;
            padding-top: 5%;
            background-color: rgb(32, 94, 102,0.6);
            border-radius: 10px;   
            margin-left: 4%;
            margin-right: 4%;
            flex-wrap: wrap;
        }
        .flexx_4{
          display: flex;
          flex-direction: row;
          justify-content: space-around;
          padding-top: 4%;
        }
        .flexx_3{
          display: flex;
          flex-direction: row;
          justify-content: left;
          padding-top: 4%;
        }
    </style>
</head>
<body>
  <div class = "flexx_4">
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" style = "background-color: rgb(32, 94, 102);" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      Sort
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li><a class="dropdown-item" href="{% url 'sort_by_popularity' %}">Popularity</a></li>
      <li><a class="dropdown-item" href="{% url 'sort_by_lowest' %}">Price Lowest First</a></li>
      <li><a class="dropdown-item" href="{% url 'sort_by_highest' %}">Price Highest First</a></li>
    </ul>
  </div>
</div>
<br>
<br>
    <div class="flexx_2">
    {% for car_detail in car_details %}
    <div class="card" style="width: 25%; border-radius: 20px; border : solid 5px white;margin-right : 5%; margin-bottom : 5%;" style = "background-color: rgb(32, 94, 102); color :rgb(32, 94, 102)">
        <img class="card-img-top" src="{{baseUrl}}/{{car_detail.photo1}}" style=" border-top-left-radius: 20px; border-top-right-radius: 20px; background-color: rgb(12, 58, 58);" alt="Card image cap" width = 200px height="170px">
        <div style = "border-radius: 20px; background-color: rgb(186, 223, 215);">
        <div class="card-body" style = "background-color: rgb(186, 223, 215);">
          <h5 class="card-title" style = "background-color: rgb(186, 223, 215);">{{car_detail.Company}} {{car_detail.Car_name}}</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item" style = "background-color: rgb(186, 223, 215);">Model : {{car_detail.Price}}</li>
          <li class="list-group-item" style = "background-color: rgb(186, 223, 215);">Model : {{car_detail.Car_Model}}</li>
          <li class="list-group-item" style = "background-color: rgb(186, 223, 215);">Car Year : {{car_detail.Car_Year}}</li>
          <li class="list-group-item" style = "background-color: rgb(186, 223, 215);">Kilometres Driven : {{car_detail.Car_KM}}</li>
        </ul>
        <div class="card-body" >
          <a href="#" class="card-link">View Details</a>
          <a href='{% url "process_request" car_detail.id %}' class="card-link">Request</a>
        </div>
      </div>
      </div>
    {% endfor %}
    </div>
    <br>
    <br>
    <br>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/comparo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static '/css/comparo.css' %}">
</head>
<body>
    <h1>Comparisions</h1>
    <form action="" method="post">
    {% csrf_token %}
    <div class="flexx">
            <input type="text" id="car1" name = "car1" placeholder="Car1" >
            <h3>VS</h3>
            <input type="text" id="car2" name = "car2" placeholder="Car2">
            <button type="submit" id="btn" class="btn">Submit</button>
    </div>
    </form>
    <br>
    <br>
    {% if car1 or car2 %}
    <div class="compare">
        <table class="table" >
            <thead>
                <tr>
                    <th class="car_name1">{{car1.name}}</th>
                    <th class="spec">SPECIFICATION</th>
                    <th class="car_name2">{{car2.name}}</th>
                </tr>
            </thead>
            <tbody> 
                <tr>
                    <td><h3 id="spec11">{{car1.Price}}</h3></td>
                    <td><h3 id="specname1">PRICE</h3></td>
                    <td><h3 id="spec21">{{car2.Price}}</h3></td>
                </tr>
                <tr>
                    <td><h3 id="spec12">{{car1.engine}}</h3></td>
                    <td><h3 id="specname2">ENGINE</h3></td>
                    <td><h3 id="spec22">{{car2.engine}}</h3></td>
                </tr>
                <tr>
                    <td><h3 id="spec13">{{car1.powertorque}}</h3></td>
                    <td><h3 id="specname3">POWER AND TORQUE</h3></td>
                    <td><h3 id="spec23">{{car2.powertorque}}</h3></td>
                </tr>
                <tr>
                    <td><h3 id="spec14">{{car1.gearbox}}</h3></td>
                    <td><h3 id="specname4">GEARBOX</h3></td>
                    <td><h3 id="spec24">{{car2.gearbox}}</h3></td>
                </tr>
                <tr>
                    <td><h3 id="spec15">{{car1.fueleconomy}}</h3></td>
                    <td><h3 id="specname5">FUEL ECONOMY</h3></td>
                    <td><h3 id="spec25">{{car2.fueleconomy}}</h3></td>
                </tr>
                <tr>
                    <td><h3 id="spec16">{{car1.wheelbase}}</h3></td>
                    <td><h3 id="specname6">WHEELBASE</h3></td>
                    <td><h3 id="spec26">{{car2.wheelbase}}</h3></td>
                </tr>
                <tr>
                    <td><h3 id="spec17">{{car1.infoitainment}}</h3></td>
                    <td><h3 id="specname7">INFOTAINMENT</h3></td>
                    <td><h3 id="spec27">{{car2.infoitainment}}</h3></td>
                </tr>
            </tbody>
        </table>
    </div>
    {% endif %}
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
    <title>PowerDrift_ABCD</title>
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <h1>Cars Made Easy</h1>
    </header>
    <nav>
        <a href="">Reviews</a>
        <a href="{% url 'comparo' %}">Comparisions</a>
        <a href="{% url 'suggest' %}">Our Suggestions</a>
        <a href="{% url 'sell' %}">Sell Used Cars</a>
        <a href="{% url 'buy' %}">Buy Used Cars</a>
        <a href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'profile' %}"><img src="{% static 'system_images/user.png' %}" width = "25px" alt="User_Image"></a>
    </nav>
    <main>
        <section>
            <div class="container">
                <i style='font-size:48px' class='fas' id="Prev">&#xf104;</i>
                <i style='font-size:48px' class='fas' id="Next">&#xf105;</i>
                <div class="slide">
                    <img src="{% static 'system_images/cre.jpg' %}" alt="Kushaq" id="lastclone" >
                    <img src="{% static 'system_images/n.jpg' %}" alt="Creta" >
                    <img src="{% static 'system_images/sel.jpg' %}" alt="Harrrier" >
                    <img src="{% static 'system_images/x7.jpg' %}" alt="Hector" >
                    <img src="{% static 'system_images/cre.jpg' %}" alt="Kushaq" >
                    <img src="{% static 'system_images/n.jpg' %}" alt="Creta" id="firstclone" >
                </div>
            </div>
            <br>
        </section>
        <h1>By Our Youtube Channel</h1>
        <section>
            <h2>Latest Car Reviews</h2>
            <iframe width="33%" height="250"src="https://www.youtube.com/embed/IYXQ1lAkLEg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250"src="https://www.youtube.com/embed/IqAfMbj5aVQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/JSPgbFZGgYw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </section>
        <section>
            <h2>Latest Comparisions</h2>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/cXbETviuWWg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/B9E86-gZ7mw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/blDerWqsT8Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </section>
        <section>
            <h2>Latest Bike Reviews</h2>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/k0UrWxEQwJo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/k0sAANZdQH0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/X8SArMHDugs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </section>
        <section>
            <h2>Latest DragRaces by us</h2>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/jiFBfBZ7Mts" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/yU59WvKPXQQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <iframe width="33%" height="250" src="https://www.youtube.com/embed/6uW6PwEVNig" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </section>
        <section>
            <br>
            <h3>Follow us on </h3>
            <br>
            <a href="https://www.instagram.com/PowerDrift/" target="_blank"><img src="{% static 'system_images/R.png' %}" alt="Instagram" width="3%" height="3%"></a>
            <a href="https://in.linkedin.com/company/powerdrift-studios-private-limited" target="_blank"><img src="{% static 'system_images/80808_linkedin-logo-white-png.png' %}" alt="Linkedin" width="3%" height="3%"></a>
            <a href="https://www.youtube.com/user/powerdriftofficial" target="_blank"><img src="{% static 'system_images/R (1).png' %}" alt="YouTube" width="3%" height="3%"></a>
            <a href="https://www.facebook.com/POWERDRIFTOFFICIAL" target="_blank"><img src="{% static 'system_images/1509135366facebook-symbol-png-logo.png' %}" alt="Facebook" width="3%" height="3%"></a>
        </section>
    </main>
    <footer>
        <a href="#">About Us</a>
        <a href="#">FAQ</a>
        <a href="#">Contact Us</a>
        <a href="#">Privacy Policy</a>
        <a href="#">Terms and Conditions</a>
    </footer>
    <script src="{% static '/js/webdev.js' %}"></script>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="{% static '/css/index.css' %}">
    <title>Document</title>
</head>
<body>
    <div  class = 'select_3'>
    <form action="{% %}" method="post">
        {% csrf_token %}
    <div class = 'select_1'>
        <select name="" id="select_company" class="form-select" >
            <option value="temp">Select Company</option>
            {% for company in companys %}
            <option value={{company.name}}>{{company.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class = 'select_1'>
        <select name="" id="select_car" class="form-select" onchange ="myopt1(this.value)">
            <option value="temp">Select Car</option>
        </select>
    </div>
    <div class = 'select_1'>
        <select name="" id="" class="form-select">
            <option value="temp">Registration Year</option>
            {% for year in years %}
            <option value={{year}}>{{year}}</option>
            {% endfor %}
        </select>
    </div>
    <div class = 'select_1'>
        <select name="" id="select_model" class="form-select">
            <option value="temp">Select Model</option>
        </select>
    </div>
    <div class = 'select_1'>
        Number of Kilometres driven: <input type="text" name="" id="" class = "form-input">
    </div>
    <div class = 'select_1'>
        Registration Number: <input type="text" name="" id="" class = "form-input">
    </div>
    {% for photo in photos %}
    <div class = 'select_1'>
    Photo {{photo}} : <input type="file" name="" id="" class = "form-input">
    </div>
    {% endfor %}
    <div class = 'select_2'>
        <input type="submit" value="Submit" class = "btn btn-primary" style = "background-color: rgb(32, 94, 102);">
    </div>
    </form>
</div>
    {% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script>

        $(document).ready(function(){
            $('select#select_company').change(function () {
                var optionSelected = $(this).find("option:selected");
                var company_name = optionSelected.text();
                $.ajax({                       
                    type: "POST",
                    url: '{% url "get_cars_ajax" %}',
                    data: {
                        'company_id': company_name,    
                        'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),   
                    },
                    success: function (data) { 
                        let html_data = '<option value="">Select Car</option>';
                        data.forEach(function (data) {
                            html_data += `<option value="${data.name}">${data.name}</option>`
                        });
                        $("#select_car").html(html_data); 
                    }
                });
            });
            });
        $(document).ready(function(){
            $('select#select_car').change(function () { 
                var optionSelected = $(this).find("option:selected");
                var car_name = optionSelected.text();
                $.ajax({                       
                    type: "POST",
                    url: '{% url "get_models_ajax" %}',
                    data: {
                        'car_id': car_name,    
                        'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),   
                    },
                    success: function (data) { 
                        let html_data = '<option value="">Select Model</option>';
                        data.forEach(function (data) {
                            html_data += `<option value="${data.name}">${data.name}</option>`
                        });
                        $("#select_model").html(html_data); 
                    }
                });
        })
    })
    </script>

    {% endblock javascript %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
    <br>
    User Name : <input type="text" name="username" id="username" class = "form-input">
    <br>
    <br>
    Password : <input type="password" name="password" id="password" class = "form-input">
    <br>
    <br>
    <input type="submit" value="Submit">
    <br>
    <br>
    </form>
    <a href="{% url 'signup' %}">Sign Up</a>
</body>
</html>

templates/sell.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
</head>
<body>
    <div  class = 'select_3'>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <div class="select_2">
        <input type="submit" value="Submit" class="btn btn-primary" style = "background-color: rgb(32, 94, 102);">
        </div>
    </form>
    </div>
    {% block javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function(){
            $('select#id_Company').change(function () {
                var optionSelected = $(this).find("option:selected");
                var company_name = optionSelected.text();
                $.ajax({                       
                    type: "POST",
                    url: '{% url "get_cars_ajax" %}',
                    data: {
                        'company_id': company_name,    
                        'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),   
                    },
                    success: function (data) { 
                        let html_data = '<option value="">Select Car</option>';
                        data.forEach(function (data) {
                            html_data += `<option value="${data.name}">${data.name}</option>`
                        });
                        $("#id_Car_name").html(html_data); 
                    }
                });
            });
            });
        $(document).ready(function(){
            $('select#id_Car_name').change(function () { 
                var optionSelected = $(this).find("option:selected");
                var car_name = optionSelected.text();
                $.ajax({                       
                    type: "POST",
                    url: '{% url "get_models_ajax" %}',
                    data: {
                        'car_id': car_name,    
                        'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),   
                    },
                    success: function (data) { 
                        let html_data = '<option value="">Select Model</option>';
                        data.forEach(function (data) {
                            html_data += `<option value="${data.name}">${data.name}</option>`
                        });
                        $("#id_Car_Model").html(html_data); 
                    }
                });
        })
    })
    </script>
    {% endblock javascript %}
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    {{field.label}}
    {{field}}
    <br>
    <br>
    {% endfor %}
    <input type="submit" value="Submit">
    {{form.errors}}
</form>
</body>
</html>